import './globals.css';
import Header from './components/common/header';
import { ThemeProvider } from './components/common/theme-provider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <ThemeProvider>
          <div className='min-h-screen bg-background text-foreground' lang='en'>
            <Header />
            <div>{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
