import './globals.css';
import Header from './components/common/header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <div className='min-h-screen bg-background text-foreground' lang='en'>
          <Header />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
